name: glow
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - nptyping=1.3.0
  - numpy=1.18.1
  - opt_einsum>=3.2.0
  - pandas=1.0.1
  - pip
  - pyarrow=1.0.1
  - pyspark=3.0.0
  - statsmodels
  - typeguard=2.9.1
  - dask
  - xarray
  - zarr
  - pip:
    - setuptools==41.2.0 # Python packaging
    - twine==2.0.0 # Pypi publishing
    - sphinx-autobuild
    - Sphinx-Substitution-Extensions # Substitutions in code blocks
    - sphinx-tabs # Code tabs (Python/Scala)
    - sybil # Automatic doctest
